name: Ruby CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 4.0.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.1'
          bundler-cache: false

      - name: Install gems
        run: |
          bundle config set frozen false
          bundle install --jobs 4 --retry 3

      - name: Run Rake
        run: bundle exec rake